# Generated by Django 4.1.5 on 2023-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=5000, null=True)),
                ('show_in_list', models.BooleanField(default=True)),
            ],
        ),
    ]
