# Generated by Django 4.1.5 on 2023-01-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='show_in_list',
            field=models.BooleanField(default=True, help_text='Yes = show the template in the list'),
        ),
    ]
